# Generated by Django 4.1.6 on 2023-02-23 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_video', models.URLField(max_length=1000, verbose_name='Ссылка на видео')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
        migrations.CreateModel(
            name='WhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_owner', models.URLField(max_length=1000, verbose_name='Ссылка WA')),
            ],
            options={
                'verbose_name': 'Ссылка WA',
                'verbose_name_plural': 'Ссылка WA',
            },
        ),
    ]
